# Generated by Django 3.2 on 2024-08-29 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerJogal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle', models.CharField(choices=[('MOTO', 'Moto'), ('AUTOMOVIL', 'Automóvil'), ('TURBO', 'Turbo'), ('CAMIONETA', 'Camioneta'), ('CARRITO', 'Carrito')], max_length=10)),
                ('license_plate', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_day', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle', models.CharField(choices=[('MOTO', 'Moto'), ('AUTOMOVIL', 'Automóvil'), ('TURBO', 'Turbo'), ('CAMIONETA', 'Camioneta'), ('CARRITO', 'Carrito')], max_length=10)),
                ('license_plate', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_day', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle', models.CharField(choices=[('MOTO', 'Moto'), ('AUTOMOVIL', 'Automóvil'), ('TURBO', 'Turbo'), ('CAMIONETA', 'Camioneta'), ('CARRITO', 'Carrito')], max_length=10)),
                ('license_plate', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_day', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
