# Generated by Django 3.2 on 2024-08-29 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle', models.CharField(choices=[('MOTO', 'Moto'), ('AUTOMOVIL', 'Automóvil'), ('TURBO', 'Turbo'), ('CAMIONETA', 'Camioneta'), ('CARRITO', 'Carrito')], max_length=50)),
                ('license_plate', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('CEDULA', 'Cédula'), ('NIT', 'NIT')], max_length=10, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('product', models.CharField(choices=[('PARKING_OCCASIONAL', 'Parqueo Ocasional'), ('MONTHLY_PAYMENT', 'Mensualidad'), ('WASH', 'Lavado')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
